### ISSUE TITLE
`rose.first()` can return None even for lists that must have an item in it

### ISSUE THREAD

**Issue by ghost** [frogtd/rose_bloom#2]
(Fails under miri)

```rust
#[test]
fn first_works() {
    extern crate std;
    use std::thread;
    let rose = Rose::new();
    rose.push(1);
    thread::scope(|s| {
        s.spawn(|| {
            for _ in 0..10 {
                rose.push(1);
            }
        });
        s.spawn(|| {
            // This should work because we pushed 1 item earlier
            // so no matter how many items we have, there's always *a* first
            for _ in 0..10 {
                rose.first().unwrap();
            }
        });
    });
}
```

Looks like an atomic memory ordering issue, where the total length and the sum total of the length of each item disagree.

It would be worth adding a promise that "after getting some value `n` from `rose.len()`, it is promised that `rose.get(x)` for any value `x` inside `0..n` will return Some". (And add a test for that)

Since that's what the current `first` code relies on anyways.

**Comment by frogtd** [comment]
I fixed the len code and rewrote first to use node traversal. Thank you again!
